### ISSUE TITLE
OK/Cancel not reachable in IE

### ISSUE THREAD

**Issue by flogehring** [TimOetting/kirby-builder#40] opened 2017-03-01 09:55 UTC
A customer just complained that they cannot save their changes in the builder blocks. 
It works fine in Chrome but in IE the button bar is stuck behind the Kirby Save bottom bar.

Apparently IE doesn't recognize the position:initial property.

![screen shot 2017-03-01 at 10 51 13](https://cloud.githubusercontent.com/assets/517510/23454744/860e9c34-fe6d-11e6-8552-ec3e3755b210.png)

**Comment by TimOetting** [comment] 2017-03-01 23:07
Hey @flogehring . Thanks for the comment. The issue is fixed now. The save bar will be hidden until you leave edit mode.

**Closed by TimOetting** 2017-03-01 23:07 UTC

**Comment by flogehring** [comment] 2017-03-02 08:54
Thanks for the quick fix!
