### ISSUE TITLE
required fields throw errors, even when filled out

### ISSUE THREAD

**Issue by theresa-g** [TimOetting/kirby-builder#184] opened 2020-10-29 09:15 UTC
Hey there!
I updated a couple of my projects to the latest kirby version (3.4.4) and suddenly noticed an issue with the required option. i cant save any of my pages anymore, if they contain a required field in a builder element. it will throw an error regardless of whether it is filled out or not and it also does not seem to matter if the field was correctly filled out pre update or if it is a new addition to the blueprint

**Comment by sebastiangreger** [comment] 2020-11-09 09:31
Looks like a duplicate of #179 - see discussion there...

**Closed** 2020-11-10 08:02 UTC
