### ISSUE TITLE
Image select for both editor and textarea doesn't work

### ISSUE THREAD

**Issue by mynameisfreedom** [TimOetting/kirby-builder#148] opened 2020-02-18 17:56 UTC
@TimOetting There is still an error when using the editor inside builder. When I select the image block inside the editor and try to **select** an image, I get the following error message:

> Invalid file model type: kirby-builder/pages/mypage/fields

_Originally posted by @RobertCordes in https://github.com/TimOetting/kirby-builder/issues/132#issuecomment-583749904_

**Comment by wout** [comment] 2020-02-19 11:41
We are having the same issue. And it's not only with an editor but also a textarea inside a builder:

![image](https://user-images.githubusercontent.com/107324/74831014-4759c580-530c-11ea-92c5-92f124fd5aef.png)

Uploading an image works, but **Select a file** shows the modal with the error above.

**Comment by jonasfeige** [comment] 2020-02-24 13:53
Same thing here for both editor and textarea.

**Comment by jonathan-reisdorf** [comment] 2020-06-24 14:13
Kirby has this very generic files route:

![grafik](https://user-images.githubusercontent.com/8958624/85572629-732be580-b635-11ea-878e-a18e8002be7e.png)

which wins over the one defined by the plugin. Unfortunately I do not see an obvious way to overwrite core API routes.

**Comment by mourique** [comment] 2020-07-08 10:07
> Kirby has this very generic files route which wins over the one defined by the plugin:

wow, nice find! 🎉 i am struggeling with the same thing and have been using the hack referenced here before: https://github.com/TimOetting/kirby-builder/issues/110#issuecomment-565712426

But this is really unstable unfortunatly.

looking into the core routes: disabling it seems to break the standard pages for files as in `/panel/pages/home/files/bildschirmfoto-2020-06-16-um-16.36.28.png` 

but changing the route to `(:all?)` as in

```php
[
     'pattern' => '(:all?)/files',
     'method'  => 'GET',
     'action'  => function (string $path) {
         return $this->parent($path)->files()->sortBy('sort', 'asc', 'filename', 'asc');
     }
],
```

seems to let the single pages for files work and also let the image chooser inside kirby builder work. This is just trial and error though. i dont know what the question mark does, i cant find it in the docs for routing. Do you know what that means @jonathan-reisdorf ? Might that be something that needs to change in kirby core?

**Comment by jonathan-reisdorf** [comment] 2020-07-10 10:13
Thanks for linking these issues together. I agree that this is ideally changed in kirby's core either by making the pattern more specific or providing a way for plugin routes to be preferred over core routes. There might also be more ways to solve this. The corresponding issue in getkirby/editor is already flagged with type: bug by the kirby author, so he's aware :)

**Comment by iskrisis** [comment] 2020-07-22 16:24
I can confirm changing 
```/kirby/config/api/routes/files``` 
line ```27``` 
from ```'pattern' => '(:all)/files',```
to ```'pattern' => '(:all?)/files',```
seems to help. I have no idea what implications of this are BUT i badly need this to work somehow so i am running with it.

**Comment by TimOetting** [comment] 2022-07-05 16:00
Closing this issue because this plugin will no longer be maintained, as its main functionality can be replaced by Kirby's built-in  [Blocks Field](https://getkirby.com/docs/reference/panel/fields/blocks) and [Layout Field](https://getkirby.com/docs/reference/panel/fields/layout).

**Closed by TimOetting** 2022-07-05 16:00 UTC
