### ISSUE TITLE
Textarea icons missing inside Kirby-Builder

### ISSUE THREAD

**Issue by jensfranke** [TimOetting/kirby-builder#107] opened 2019-03-24 08:26 UTC
Field-Definition:
```
label: Text
type: textarea
buttons:
  - link
  - email
```

Page-Definiton:
```
fields:
  text:
    extends: fields/textarea
  modules:
    label: Builder
    type: builder
    fieldsets:
      sectiontext:
        fields:
          text:
            extends: fields/textarea
```

Inside the Pagebuilder one icon is missing:

<img width="827" alt="Bildschirmfoto 2019-03-24 um 09 23 36" src="https://user-images.githubusercontent.com/595504/54876828-b71eb200-4e16-11e9-9e9d-8a11db5f727c.png">

**Comment by jensfranke** [comment] 2019-04-08 05:14
The same problem is with fields of the type select, radio und checkbox.

![Bildschirmfoto 2019-04-08 um 07 13 40](https://user-images.githubusercontent.com/595504/55700010-dc422180-59cd-11e9-81c1-df3d64fd8c06.png)

**Comment by TimOetting** [comment] 2019-08-14 23:58
I could not reproduce this error with the current version 2.0.13. Can you confirm this?

**Comment by TimOetting** [comment] 2022-07-05 16:01
Closing this issue because this plugin will no longer be maintained, as its main functionality can be replaced by Kirby's built-in  [Blocks Field](https://getkirby.com/docs/reference/panel/fields/blocks) and [Layout Field](https://getkirby.com/docs/reference/panel/fields/layout).

**Closed by TimOetting** 2022-07-05 16:01 UTC
